package models.utils;

public enum State {
    CHOOSING_ROLE,

    DRIVER_ACTIVE,
    NO_TRIPS_AVAILABLE,
    DRIVER_TOOK_TRIP,

    DRIVER_INACTIVE,

    ENTERING_ADDRESS,
    ENTERING_DETAILS,
    CHECKING_OUT_ON_STATION,
    ENTERING_ON_STATION,

    APPROVING_TRIP,
    LOOKING_FOR_DRIVER,
    FOUND_A_CAR
}
