package models.utils;

public enum State {
    CHOOSING_ROLE,

    DRIVER_ACTIVE,
    DRIVER_ENTERING_NUMBER,
    NO_TRIPS_AVAILABLE,
    DRIVER_TOOK_TRIP,
    AM_GOOD_BOY,

    DRIVER_INACTIVE,

    ENTERING_ADDRESS,
    ENTERING_DETAILS,
    ENTERING_NUMBER,

    EDITING_DETAILS,
    EDITING_ADDRESS,

    APPROVING_TRIP,
    TRY_AGAIN_DURING_CURFEW,

    LOOKING_FOR_DRIVER,
    TRIP_SEARCH_STOPPED,
    FOUND_A_CAR
}
